openapi: 3.0.1
info:
  title: quality
  description: API Definition of quality
  version: 1.0.0
servers:
- url: http://localhost:8290/qa
paths:
  /inspections:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /reports:
    get:
      responses:
        default:
          description: Default response
