apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
    name: opensearch
    namespace: observability
spec:
    general:
        setVMMaxMapCount: true
        serviceName: opensearch
        version: 2.15.0
    dashboards:
        enable: true
        version: 2.15.0
        replicas: 1
        additionalConfig:
            opensearchDashboards.branding.logo.defaultUrl: "https://raw.githubusercontent.com/chathurace/observability-resources/main/images/wso2-dashboard-logo.png"
            opensearchDashboards.branding.mark.defaultUrl: "https://raw.githubusercontent.com/chathurace/observability-resources/main/images/wso2-dashboard-icon.png"
            opensearchDashboards.branding.loadingLogo.defaultUrl: "https://raw.githubusercontent.com/chathurace/observability-resources/main/images/loading.png"
            opensearchDashboards.branding.applicationTitle: "WSO2 Dashboard" 
    nodePools:
        - component: master
          replicas: 3
          diskSize: "3Gi"
          resources:
              requests:
                  memory: "1000Mi"
                  cpu: "100m"
              limits:
                  memory: "1100Mi"
                  cpu: "250m"
          roles:
              - "master"
        - component: data
          replicas: 1
          diskSize: "5Gi"
          resources:
              requests:
                  memory: "1000Mi"
                  cpu: "500m"
              limits:
                  memory: "1100Mi"
                  cpu: "800m"
          roles:
              - "data"
    security:
        tls:
            transport:
                generate: true
            http:
                generate: true
