shipmentHost="shipments-svc:9101"

[ballerina.observe]
tracingEnabled=true
tracingProvider="jaeger"
metricsLogsEnabled=true

[ballerinax.jaeger]
agentHostname="data-prepper.observability.svc.cluster.local"
agentPort=4317
samplerType="const"
samplerParam=1.0
reporterFlushInterval=2000
reporterBufferSize=1000
