shipmentHost="shipments-svc:9101"
crmHost="crm-svc:9102"
inventoryHost="inventory-svc:9103"
bookParkHost="bookpark-svc:8290"

[ballerina.observe]
tracingEnabled=true
tracingProvider="jaeger"

[ballerinax.jaeger]
agentHostname="data-prepper.observability.svc.cluster.local"
agentPort=4317
samplerType="const"
samplerParam=1.0
reporterFlushInterval=2000
reporterBufferSize=1000
