entry-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      port: 4317
      ssl: false
  sink:
    - pipeline:
        name: "raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"
    - stdout: {}
raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
        hosts: [ "https://opensearch-data.observability.svc.cluster.local:9200" ]
        username: "{{ .Values.opensearch.username }}"
        password: "{{ .Values.opensearch.password }}"
        insecure: true        
        index_type: trace-analytics-raw
service-map-pipeline:
  delay: "100"
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - service_map_stateful:
  sink:
    - opensearch:
        hosts: ["https://opensearch-data.observability.svc.cluster.local:9200"]
        username: "{{ .Values.opensearch.username }}"
        password: "{{ .Values.opensearch.password }}"
        insecure: true
        index_type: trace-analytics-service-map
